BACKBONE:
  MODEL_TYPE: "convnext"
  OUT_CHANNELS: 128
  DROP_PATH: 0.3
BRIDGEDEPTH:
  ENCODER_VIT: "vitl"
  RECURRENT_LOSS_WEIGHT: 1.0
  RECURRENT_LOSS_GAMMA: 0.8
DPN:
  MAX_DISP: 416
  NUM_PROPOSALS: 2
NMP:
  REFINE_WINDOW_SIZE: 4
  USE_FLASH_ATTN: False
DATASETS:
  TRAIN: ("sceneflow", "fsd", "sintel_stereo", "crestereo", "in_stereo2k", "falling_things", "vkitti2")
  MUL: (15, 1, 100, 3, 100, 8, 30)
  TEST: ("kitti_2012_trainval", "kitti_2015_trainval", "eth3d", "middlebury_Q")
  CROP_SIZE: [320, 736]
TEST:
  EVAL_THRESH: (['3.0'], ['3.0'], ['1.0'], ['2.0'])
  EVAL_MAX_DISP: [null, null, null, 1000]
  EVAL_ONLY_VALID: (True, True, True, False)
  EVAL_PROP: (True, True, True, True)
SOLVER:
  # NO_RESUME_OPTIMIZER: True
  IMS_PER_BATCH: 24
  MAX_ITER: 500000
  CHECKPOINT_PERIOD: 10000
  MAX_DISP: 416
  BASE_LR: 0.0005
  BASE_LR_END: 0.00001
DATALOADER:
  NUM_WORKERS: 24